const EErrors = {
  USER_ALREADY_EXIST: 1,
  USER_NOT_EXIST: 2,
  INVALID_USER: 3,
  INVALID_USER_PARAMS: 4,

  INVALID_PRODUCT_PARAMS: 5,
  INVALID_PRODUCT_THUMBNAIL: 5,
  NO_EXIST_PRODUCT: 6,

  NO_EXIST_CART: 6,
  INSUFFICIENT_STOCK: 7,
  EMPTY_CART: 8,
  ERROR_CREATING_USER: 9,

  NOT_AUTHORIZED: 10,
};

export default EErrors;
